INSERT INTO admin(name, pass) VALUES("Drakos", "123123");
INSERT INTO admin(name, pass) VALUES("MentalChaos", "qwe");

INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016689-0', 'MAICOL IGNACIO', 'ACEVEDO GONZALEZ', '1A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20170736-6', 'ROSALINDA MARCELA', 'ACEVEDO MARTINEZ', '2A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20801747-0', 'BARBARA JAVIERA', 'ACEVEDO GAVILAN', '3A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20351048-9', 'CRISTIAN ANDRES', 'ADASME ALCAINO', '4A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20563177-1', 'ALEXANDER JESUS', 'ALARCON FUENTES', '5A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20993842-1', 'BARBARA DEL PILAR', 'ALARCON CARRASCO', '6A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20560818-4', 'MARIA ANA GEMMA', 'ALEGRIA PERALTA', '7A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20881297-K', 'EFRAIN SAUL', 'ALEGRIA PERALTA', '8A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20997639-0', 'DARLYN JEIMY DAFNE', 'ALMENDRAS ORELLANA', '1A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802453-1', 'ANITA MARIA', 'ANDRADES MADRIGAL', '2A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016442-1', 'JAEL ANTONIA', 'ANDRADES PARRA', '3A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20563740-0', 'THOMAS ANTONIO', 'ARANGUIZ BARRAZA', '4A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802821-9', 'ABIGAIL MARLENE', 'ARAVENA corales', '5A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20562905-K', 'DORILA DEL CARMEN', 'ARAVENA DIAZ', '6A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20829779-1', 'NATALIA ANYELINA', 'ARAYA GONZALEZ', '7A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016737-4', 'NICOLE VALERIA', 'ARAYA VALENCIA', '8A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802305-5', 'MARCELA ANTONIA', 'ARAYA CASTRO', '1A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20823755-1', 'ANTONIA FERNANDA', 'ARENAS AGUIRRE', '2A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20945882-9', 'DAMARYS YESSENIA', 'ARIAS RETAMAL', '3A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20564345-1', 'JAVIERA IGNACIA', 'ARRIAGADA ARELLANO', '4A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20813200-8', 'ALEXANDRA JANETTE', 'ASTETE VERGARA', '5A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016278-K', 'MERIS MAGDALENA', 'AVILA RIVAS', '6A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20801804-3', 'JAZMIN CATALINA', 'BAHAMONDES DIAZ', '7A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20692775-5', 'ESKARLETH LISBETH', 'BARRERA MORALES', '8A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21015971-1', 'MARIA PAZ', 'BASOALTO IGOR', '1A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20801946-5', 'DEBORA JACQUELINE', 'BENAVIDES ZUÑIGA', '2A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20564896-8', 'FERNANDA IGNACIA', 'BERRIOS DURÁN', '3A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20563656-0', 'CARLA CONSTANZA', 'BERRIOS ORTIZ', '4A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802665-8', 'PAMELA STEFANIA', 'BRAVO CANCINO', '5A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20927753-0', 'HILLARY ANDREA', 'BRAVO PACHECO', '6A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20803008-6', 'MARTINA BELEN', 'BRAVO SEPULVEDA', '7A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20803376-K', 'SOFIA MACARENA', 'BRAVO QUIROZ', '8A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016633-5', 'KARLA ANDREA', 'BRAVO VILCHES', '1A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016296-8', 'CONSTANZA ESTEFANI', 'BRAVO ROJAS', '2A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802024-2', 'CLAUDIO ALEXANDER', 'BRAVO MARTINEZ', '3A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20717812-8', 'CAMILA ALEJANDRA', 'BRICEÑO GARCIA', '4A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802634-8', 'SABRINA MICHELLE DEL CARMEN', 'BUSTAMANTE ROJAS', '5A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016481-2', 'CARLA ANTONIA', 'CABALLERO RIQUELME', '6A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20397776-K', 'MARIA CRISTINA', 'CABRERA NILO', '7A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20692834-4', 'FABIOLA BELEN', 'CACERES CACERES', '8A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20961368-9', 'JAVIERA FERNANDA CONSTANZA', 'CACERES ARANCIBIA', '1A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20837641-1', 'SCARLET LISETTE', 'CACERES MUÑOZ', '2A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21008749-7', 'LETICIA DEL PILAR 20801', 'CÁCERES MIRANDA', '3A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21008089-9', 'YULISSA LINZAHY', 'CAMPOS FUENTES', '4A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802767-0', 'ANGELA NATALIE', 'CAMPOS RIOSECO', '5A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21026335-7', 'DAMARIS TABITA', 'CAMPOS JAQUE', '6A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016595-9', 'MARIA ELIANA DEL CARMEN', 'CANALES ZUÑIGA', '7A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20803156-2', 'FRANCISCA PAZ', 'CANCINO PAZ', '8A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20565455-0', 'BRAYAN ALEJANDRO', 'CANCINO SANDOVAL', '1A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20562854-1', 'CONSTANZA ESTEFANI', 'CANCINO BECERRA', '2A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016166-K', 'VALENTINA MONSERRATT', 'CANDIA RUIZ', '3A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20843876-K', 'BARBARA GERALDINE', 'CARCAMO MUÑOZ', '4A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20723949-9', 'ARACELY FERNANDA', 'CARREÑO AVACA', '5A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20565561-1', 'SOFIA VALENTINA', 'CARTES CAMPOS', '6A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802017-K', 'CONSTANZA CAROLINA', 'CARTES GUTIERREZ', '7A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20996212-8', 'MICHELLE ANTONIA', 'CARVAJAL CARCAMO', '8A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20388201-7', 'LISBETH CAROLINA', 'CASTILLO FONSECA', '1A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20937338-6', 'IGNACIA DEL CARMEN', 'CASTRO MIÑO', '2A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20919218-7', 'KRISHNA ALEXANDRA', 'CASTRO PAVEZ', '3A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20538333-6', 'FRANCISCA SOLEDAD', 'CASTRO PONCE', '4A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20305810-1', 'GISELL JARLYHEIN', 'CERRO SALAZAR', '5A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20801722-5', 'ANIBAL PATRICIO', 'CISTERNA CISTERNA', '6A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20996049-4', 'YURIANA ANDREA', 'COFRE VERGARA', '7A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20987429-6', 'VALENTINA PAZ', 'CONTARDO OYARCE', '8A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20997006-6', 'CECILIA FERNANDA', 'CONTRERAS FAUNDEZ', '1A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016155-4', 'NATALIA EUGENIA', 'CONTRERAS CANIUQUEO', '2A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016727-7', 'JOCELIN ALEJANDRA', 'CONTRERAS MIÑO', '3A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20307072-1', 'VALENTINA ISADORA', 'CORDERO ACUÑA', '4A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20909913-6', 'DANAE DE LOS ANGELES', 'CORNEJO ORELLANA', '5A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20788427-8', 'YAMILET GABRIELA', 'CORNEJO LETELIER', '6A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20349973-6', 'FLOR ALEJANDRA', 'DIAZ GARRIDO', '7A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016357-3', 'KATHERINE ALEXANDRA', 'DIAZ OPAZO', '8A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20068934-8', 'ALVARO TOMAS', 'DIAZ RAMOS', '1A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20563901-2', 'KRISHNA DEL CARMEN', 'DIAZ ACUÑA', '2A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20729781-K', 'SCARLETT JAVIERA', 'DIAZ ROJAS', '3A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20834629-6', 'JAVIERA FERNANDA', 'DOMINGUEZ MOLINA', '4A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20565654-5', 'ISNALDA DAMARIS', 'ESCAMILLA LOYOLA', '5A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21015967-3', 'MICHEL ESTEFANIA', 'ESPINOSA GONZALEZ', '6A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20803092-2', 'JAVIERA ANTONIA', 'ESPINOZA MUÑOZ', '7A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802669-0', 'LISSETTE ALAXANDRA', 'ESPINOZA ALFAN', '8A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20281280-5', 'CATALINA ISABEL', 'FILGUEIRA OYANEDEL', '1A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20882136-9', 'NATALIA ALEXANDRA', 'FLORES ALBORNOZ', '2A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20351196-5', 'CATHERINE FRANCISCA', 'FLORES GONZALEZ', '3A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20169692-5', 'PATRICIA ANDREA', 'FUENTEALBA VASQUEZ', '4A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20531197-1', 'DANIELA FERNANDA', 'FUENTES NUÑEZ', '5A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016119-8', 'CONSTANZA ILIETE', 'FUENTES VENEGAS', '6A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20564559-4', 'CAROLAIN ALEXSANDRA NICOL', 'FUENZALIDA NUÑEZ', '7A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21015911-8', 'KARLA ORIANA', 'GAETE CARRION', '8A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20801752-7', 'GEHISON BENJAMIN', 'GALAZ ARENAS', '1A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20801596-6', 'DANIEL ARMANDO', 'GALVEZ FUENTES', '2A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20565698-7', 'NADIA ANAIS', 'GALVEZ GAJARDO', '3A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016107-4', 'KLER ALEXANDRA', 'GARCIA CONCHA', '4A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802704-2', 'NICOLAS ALEXIS', 'GARRIDO GUAJARDO', '5A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016740-4', 'CATALINA MILLARAY', 'GARRIDO FUENTES', '6A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21013587-1', 'BARBARA CONSTANZA', 'GARRIDO CONCHA', '7A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20801586-9', 'FRANCISCA IGNACIA', 'GARRIDO CARVAJAL', '8A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802371-3', 'ESPERANZA ISIDORA', 'GARRIDO RAMOS', '1A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20434994-0', 'KEVIN ALEXANDER', 'GONZALEZ CANO', '2A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20564033-9', 'MICHELLE MARGARITA', 'GONZALEZ FLORES', '3A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20845923-6', 'KAREN PAULINA', 'GONZALEZ SANTANDER', '4A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802264-4', 'BARBARA ALEJANDRA', 'GONZALEZ TORRES', '5A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20944975-7', 'JAVIERA ANTIONIA', 'GONZALEZ CALBUL', '6A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20723364-1', 'KEVIN SEBASTIAN', 'GONZALEZ SAZO', '7A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016484-7', 'CONSTANZA ALEJANDRA', 'GONZALEZ ROJAS', '8A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20944799-1', 'CAROL BELEN', 'GRANDON BARAHONA', '1A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20304910-2', 'SEBASTIAN IGNACIO', 'GRANDON BARAHONA', '2A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20919898-3', 'DIANA ANDREA', 'GUERRA TORRES', '3A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20801598-2', 'MARIA ELIANA', 'GUERRERO POBLETE', '4A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20654109-1', 'FRANCHESKA EMILIA', 'HENRIQUEZ REYES', '5A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20141084-3', 'ISMAEL ALBERTO', 'HENRIQUEZ GONZALEZ', '6A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20833510-3', 'BELEN ALEJANDRA', 'HERNANDEZ RAMIREZ', '7A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20565243-4', 'SUSANA MARGARITA', 'HERRERA MUÑOZ', '8A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20974629-8', 'MIRIAM SOLANGE', 'HERRERA ORELLANA', '1A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20693306-2', 'VALENTINA IGNACIA', 'HERRERA POBLETE', '2A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21036889-K', 'NAZARET KATALINA', 'HERRERA AVILA', '3A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20070990-K', 'CLAUDIA ALEJANDRA', 'HORTA PALMA', '4A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20801794-2', 'SONIA DEL CARMEN', 'ICETA CASTRO', '5A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20942338-3', 'PAZ BELEN', 'ILUFI FIGUEROA', '6A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20920298-0', 'YIPSIA SARAY', 'INOSTROZA RIOSECO', '7A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20881643-8', 'YASMIN ALEJANDRA', 'INZULZA ARAYA', '8A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20803190-2', 'LUCRECIA CONSTANZA', 'ITURRA TOLOZA', '1A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20998070-3', 'MARCO ANTONIO', 'JAQUE VALENZUELA', '2A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21017009-K', 'FERNANDA ISIDORA', 'JARA RIVERA', '3A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20939926-1', 'SEBASTIAN ANDRES', 'JARA BENAVIDES', '4A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802783-2', 'ANA ESCARLET', 'JARA GONZALEZ', '5A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20171385-4', 'ANA MARIA', 'JARA MARTINEZ', '6A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20657377-5', 'WIKI DIXIE', 'JORQUERA MONSALVE', '7A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20705538-7', 'PAULINA ISABEL', 'JORQUERA FIGUEROA', '8A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016732-3', 'ESTEFANI FRANCISCA', 'LARA LARA', '1A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20304814-9', 'HELLEN SCARLETT', 'LARA CEPEDA', '2A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016732-K', 'ESTEFANI FRANCISCA', 'LARA LARA', '3A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20845368-8', 'GIOVANKA BELEN', 'LAVIN CARRASCO', '4A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20171121-5', 'MANUEL PATRICIO', 'LEPE VALENZUELA', '5A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20563207-7', 'TIARE ANDREA', 'LETELIER HIDALGO', '6A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20905100-1', 'FABIAN IGNACIO', 'LOPEZ ALIAGA', '7A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20789123-1', 'JAVIERA PAZ', 'LOPEZ FLORES', '8A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802032-3', 'JAVIERA ANTONIA', 'LOPEZ DURAN', '1A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20803230-5', 'LLANARA ESTEFANI', 'LÓPEZ DÍAZ', '2A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21021913-7', 'FERNANDA IVONNE', 'LORCA ABURTO', '3A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20350369-5', 'BELEN PILAR', 'LUNA SALAS', '4A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20886435-1', 'NATALY VALENTINA', 'LUNA SALAS', '5A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20801007-2', 'CONSTANZA MARIBEL', 'MACHUCA GARCIA', '6A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21794334-5', 'ESPERANZA ARACELY', 'MANRIQUEZ SCHUFFENEGGER', '7A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20886251-0', 'KARLA BELEN', 'MANZOR ALARCON', '8A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20829676-0', 'JAVIERA MONSERRAT', 'MARABOLI LETELIER', '1A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20803312-3', 'VALENTINA ANTONIA', 'MARCHANT MORALES', '2A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20803079-5', 'CONSTANZA ISABEL', 'MARISCAL ALARCON', '3A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20803061-2', 'MARIA PAZ', 'MARTINEZ MONTECINO', '4A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20565016-4', 'VÍCTOR FRANCISCO', 'MARTINEZ VILLEMAINE', '5A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016470-7', 'VALENTINA CONSTANZA', 'MARTINEZ JAQUE', '6A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20801686-5', 'MARIA JOSE', 'MARTINEZ ARANCIBIA', '7A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20801599-0', 'FRANCHESCA DEL CARMEN', 'MARTINEZ PEREZ', '8A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016118-K', 'LIGIA PATRICIA', 'MATURANA TRONCOSO', '1A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016097-3', 'JAZMIN ESTEFANIA', 'MAURERIA SEGUEL', '2A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20803313-1', 'EMILIA BERNARDITA', 'MEDINA BERRIOS', '3A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016429-4', 'SARA BELEN', 'MELENDEZ CASTILLO', '4A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802261-K', 'CARLA JAZMIN', 'MENDEZ ALBORNOZ', '5A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20831454-8', 'CONSTANZA BELEN', 'MIQUELES SAEZ', '6A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20306432-2', 'PRISCILLA ESMERALDA', 'MIRANDA ROJAS', '7A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20837309-9', 'CHRISTIAN ALEXANDER PATRICIO', 'MONJE GONZALEZ', '8A');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802053-6', 'SOLEDAD FRANCISCA', 'MONSALVE ROJAS', '1B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20334421-K', 'JAVIERA IGNACIA', 'MONTECINO SEPULVEDA', '2B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20564216-1', 'PÍA VALENTINA', 'MONTECINOS GONZALEZ', '3B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20564225-0', 'GUILLERMO JESUS', 'MONTECINOS VELIZ', '4B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('16321080-0', 'CATALINA CONSTANZA', 'MONTERO CASTRO', '5B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20564859-3', 'HECTOR ANDRES', 'MORALES ESPINOZA', '6B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20565162-4', 'VALENTINA JAVIERA', 'MORALES FUENTES', '7B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20307494-8', 'DORALISA DEL CARMEN', 'MORENO GOMEZ', '8B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21015947-9', 'KRISNN JUDITH', 'MOYA SEPULVEDA', '1B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20623531-4', 'JAVIERA ISIDORA PAZ', 'MUÑOZ RIQUELME', '2B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20070284-0', 'VIVIANA DEL CARMEN', 'MUÑOZ SAAVEDRA', '3B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20784381-4', 'KATHERINE ALEJANDRA', 'MUÑOZ HERNANDEZ', '4B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20984840-6', 'IGNACIO ANDRES', 'MUÑOZ RIQUELME', '5B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20350515-9', 'ESTEFANIA DE LOS ANGELES', 'MUÑOZ CASTRO', '6B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20564798-8', 'KEVIN ALBERTO', 'MUÑOZ BURGOS', '7B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20987705-8', 'JAVIERA BELEN', 'MUÑOZ VALENZUELA', '8B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21002329-1', 'ROXANA ANDREA', 'MUÑOZ DIAZ', '1B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('22453361-6', 'ANTONELLA ROCIO', 'NEIRA RIVAS', '2B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20692861-1', 'MARTA ISABEL', 'NOVOA PALACIOS', '3B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20837147-9', 'SCARLETH JOSEFINA', 'NUÑEZ FLORES', '4B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20958386-0', 'ANA IRIS', 'OLAVE MATURANA', '5B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20307389-5', 'FABIAN ALEJANDRO', 'OLAVE QUINTANA', '6B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20562785-5', 'LUCERO VALERIA', 'OLGUIN RODRIGUEZ', '7B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20008464-0', 'JUDITH BELEN', 'OPAZO ROJAS', '8B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20305794-6', 'JENIFER ARACELY', 'ORELLANA MERCADO', '1B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20169529-5', 'JOSEFA ISADORA', 'ORELLANA VALENZUELA', '2B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20803026-4', 'NAYARETH ALYN', 'ORELLANA AVILA', '3B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20803373-5', 'CAMILA ANDREA', 'ORIAS ARANCIBIA', '4B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20724733-2', 'RICHARD ANTONIO', 'ORTEGA CACERES', '5B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016175-9', 'CAMILA ANDREA', 'ORTEGA ORTEGA', '6B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20905301-2', 'PAMELA ANDREA', 'ORTIZ DOMINGUEZ', '7B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802009-9', 'CATHERINE ALEJANDRA', 'OSSES MUÑOZ', '8B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802234-2', 'SCARLETH BEATRIZ', 'PACHECO JARA', '1B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20565025-3', 'MARIA IGANACIA', 'PADRON POBLETE', '2B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20654133-4', 'YASMIN ALEJANDRA', 'PALOMERO MUÑOZ', '3B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20307554-5', 'CAMILA FERNANDA', 'PEÑA ESPINOZA', '4B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802673-9', 'CARLA ROCIO', 'PEÑALOZA MOLINA', '5B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20803111-2', 'JAVIERA IGNACIA', 'PEREZ ALMUNA', '6B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802354-3', 'JUDITH ANTONIA', 'PEZOA VALDEBENITO', '7B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20986863-6', 'ANALIS VALENTINA', 'PINO ORELLANA', '8B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20803087-6', 'MARIA DEL CARMEN', 'PITICAR MOYA', '1B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016721-8', 'MILARAY ALEXANDRA', 'POBLETE VALDES', '2B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20844371-2', 'DENIS ESTER SOLEDAD', 'POBLETE ROJAS', '3B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20906410-3', 'MILLARAY FERNANDA', 'PONCE VERGARA', '4B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20914265-1', 'VALERY LORETO', 'PONCE GONZALEZ', '5B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20350723-2', 'KATHALINA DANAE', 'PRIETO BARRIOS', '6B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20963987-4', 'MATIAS NICOLAS', 'PUGA ARDILES', '7B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20351018-7', 'SOLANGE ANDREA', 'QUILODRAN DIAZ', '8B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20565255-8', 'VALENTINA ALEJANDRA', 'QUINTEROS QUEZADA', '1B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20171128-2', 'EFRAIN IGNACIO', 'RAMIREZ VASQUEZ', '2B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20917958-K', 'MARIBEL YESSENIA', 'RAMIREZ RODRIGUEZ', '3B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20307096-9', 'YANET DEL CARMEN', 'RAMIREZ MANQUEAN', '4B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016734-K', 'LA FUENTE VALENTINA ANDREA', 'REBECO DE', '5B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21006269-6', 'DEISSY ANNAIS', 'REBOLLEDO CASTRO', '6B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20656466-0', 'CONSTANCE RACHEL', 'REYES EGUILUZ', '7B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20783639-7', 'TAMARA ANDREA', 'REYES CERPA', '8B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802681-K', 'KRISHNA ALEXANDRA', 'RIOS ROJAS', '1B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21010965-K', 'ESPERANZA ESTRELLA', 'RIQUELME HIDALGO', '2B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20785545-6', 'ROCIO BELEN', 'ROA BORQUEZ', '3B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20883351-0', 'MAIRA FERNANDA', 'ROBLEDO MENA', '4B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20912104-2', 'DARLYN JULIETTA', 'ROCO MORALES', '5B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20801693-8', 'DANIELA DEL CARMEN', 'RODRIGUEZ ROJAS', '6B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20824660-7', 'TANIA VALENTINA', 'RODRIGUEZ ESPARZA', '7B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20520356-7', 'KATIA ANDREA', 'ROJAS MUÑOZ', '8B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20070771-0', 'CESAR ANTONIO', 'ROJAS VASQUEZ', '1B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20801606-7', 'KRICHNA FERNANDA', 'ROJAS VALENZUELA', '2B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20729671-6', 'TAMARA YUBITZA', 'ROJAS ANIÑIR', '3B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20564404-0', 'TAMARA CONSTANZA', 'ROJAS FUENTES', '4B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20306005-K', 'ALIAN PATRICIO', 'ROJAS FUENTES', '5B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20829376-1', 'ANTONIA CAROLINA', 'ROJAS MANCILLA', '6B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20801660-1', 'BARBARA ANDREA', 'ROJAS RIQUELME', '7B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20865817-4', 'LINKA DAYNNA', 'ROJAS MUÑOZ', '8B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20563840-7', 'ALEXANDRA BELEN', 'ROJAS TAPIA', '1B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20803314-K', 'FERNANDA IGNACIA', 'ROJAS ROJAS', '2B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20803037-K', 'SASHA ALONDRA', 'ROMERO ORTIZ', '3B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20785687-8', 'VALERIT POLLET', 'ROSALES ROJAS', '4B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20768334-5', 'DAMARI JAVIERA', 'RUBIO RIVERA', '5B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802437-K', 'ANTONIA IGNACIA', 'SALAS PIGATTI', '6B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20350246-K', 'ANTONELLA ALEXANDRA', 'SALAS SOTO', '7B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20803381-6', 'MIRYAM ALEJANDRA', 'SALAS LARA', '8B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20982997-5', 'CAMILA FERNANDA', 'SALAZAR TAPIA', '1B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20918902-K', 'VALENTINA ANDREA', 'SALINA EPULEF', '2B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20918892-2', 'ELIZABETH EVANICA', 'SALINAS EPULEF', '3B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21009917-4', 'CAROLINA IGNACIA', 'SANCHEZ VASQUEZ', '4B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802430-2', 'CATALINA ALEXANDRA', 'SANCHEZ URBINA', '5B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802601-1', 'PAOLA VALENTINA', 'SANCHEZ ARAYA', '6B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016437-5', 'VALENTINA PAZ', 'SANDOVAL BRAVO', '7B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20803439-1', 'COSTANZA ALEJANDRA', 'SANDOVAL REBOLLEDO', '8B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20991107-8', 'ESTEBAN PATRICIO', 'SANDOVAL LAGOS', '1B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20845917-6', 'KATHERINE LISETTE', 'SARABIA RIVERA', '2B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20948918-K', 'NICOL ESPERANZA', 'SEPULVEDA BRAVO', '3B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20757346-9', 'YESNARIN IVONN', 'SEPULVEDA COFRE', '4B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21043646-4', 'CATALINA FRANCHESCA', 'SEPULVEDA OLIVEROS', '5B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20565419-4', 'DAHIANA SOLANGE', 'SEPULVEDÁ GONZALEZ', '6B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016388-3', 'DEBORA VALENTINA', 'SEPULVEDA MORALES', '7B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016521-5', 'ROMINA IVONNE', 'SILVA COFRE', '8B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20563583-1', 'SUSANA LEONOR', 'SOTO MARISCAL', '1B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802595-3', 'MAURICIO ALEJANDRO', 'SOTO GARRIDO', '2B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016208-9', 'DIEGO ANDRES', 'SOTO MIÑO', '3B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20813145-1', 'MATIAS EDUARDO', 'SOTO HEREERA', '4B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20886126-1', 'NICOL ALEJANDRA', 'SOTO MALDONADO', '5B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21040372-8', 'AARON SAMUEL', 'SOTO VALENCIA', '6B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20565651-0', 'LAURA CATALINA', 'STULL VIDAL', '7B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21062711-1', 'NELLY ELIANA', 'SUAZO REYES', '8B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016492-8', 'MARIA INES', 'TAPIA PARADA', '1B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20307656-8', 'VANESSA VALENTINA', 'TIRAPEGUI VASQUEZ', '2B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20803109-0', 'DAISY CATALINA', 'TOLEDO FARIAS', '3B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20563404-5', 'CATALINA ANAIS', 'TOLEDO TOLEDO', '4B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20350843-3', 'CATALINA DEL PILAR', 'TORO ROJAS', '5B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20739790-3', 'GERALDINE ANAHI', 'TORRES GONZALEZ', '6B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20306936-7', 'CATALINA ALEJANDRA', 'URBINA CACERES', '7B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20563358-8', 'SANDRA MAUREEN', 'URBINA CAMPOS', '8B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802300-4', 'VICTOR MANUEL', 'URRA SOTO', '1B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20823649-0', 'FRANCISCA NOEMI', 'URRUTIA FUENTES', '2B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20580957-0', 'INGRID CATALINA ALEJANDRA', 'VALDES ARANCIBIA', '3B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20350975-8', 'NATALY SOLANGHE MAGDALENA', 'VALDES URRIOLA', '4B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802907-K', 'ESTEFANIA ALEJANDRA', 'VALENZUELA PALACIOS', '5B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802227-K', 'YENIFER INES', 'VALENZUELA CASADILLA', '6B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20803372-7', 'MARTIN MERCEDES ALEXIS', 'VALENZUELA SAN', '7B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20565658-8', 'ALICIA MILENKA', 'VALENZUELA IBAÑEZ', '8B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20564067-3', 'CRISTOFER GERARDO', 'VALENZUELA CASTILLO', '1B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20393153-0', 'MATIAS ALEXIS', 'VALENZUELA GAETE', '2B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20564181-5', 'NATALIA JAVIERA', 'VALLEJO MATURANA', '3B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20915354-8', 'LLULISSA GRISELLE', 'VASQUEZ RAMIREZ', '4B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21062531-3', 'ALEXSANDER NOEL', 'VENEGAS VENEGAS', '5B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20847996-2', 'FERNANDA LISETH', 'VERA SEPULVEDA', '6B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20801751-9', 'CAMILA ANDERA', 'VERDUGO SAAVEDRA', '7B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20564251-K', 'LISETTE CONSTANZA', 'VERDUGO HORMAZABAL', '8B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20801767-5', 'PAOLA IGNACIA', 'VERGARA CONTRERAS', '1B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016402-2', 'NAYERLI DEL PILAR', 'VILCHES MONTERO', '2B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20803388-3', 'JANIS SCARLET', 'VILCHES REYES', '3B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802645-3', 'IGNACIO ESTEBAN', 'VILCHES ROJAS', '4B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20803039-6', 'YASKAREL ALEXANDRA', 'VILLAGRA VILLAGRA', '5B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21015886-3', 'GENESIS BELEN DEL PILAR', 'YAÑEZ GAETE', '6B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20563834-2', 'FELIPE ANTONIO DE JESÚS', 'ZUÑIGA PARRA', '7B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20975111-9', 'NOEMI ANGELICA', 'ZUÑIGA MUÑOZ', '8B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20351188-4', 'CIOMARA IGNACIA', 'ABACA MONTECINO', '1B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20170971-7', 'HUGO ESTEBAN JORDANO', 'ACEVEDO SOTO', '2B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20306301-6', 'ESTEBAN JESUS', 'ADASME BRAVO', '3B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20227289-4', 'GABRIELA SOLEDAD', 'ALARCON SERRANO', '4B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20801764-1', 'JAVIERA FRANCISCA', 'ARAVENA HERNANDEZ', '5B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20787746-8', 'CRISHTOPHER SEBASTIAN', 'ASTUDILLO MUÑOZ', '6B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20305433-5', 'CATALINA FERNANDA', 'BALLADARES GOMEZ', '7B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20740836-0', 'DANICSA ANDREA', 'BINILLA RAMIREZ', '8B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802655-0', 'CONSTANZA ALEXANDRA', 'BURGOS TOLEDO', '1B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20803203-8', 'ARACELLI CATALINA', 'BUSTAMANTE HERRERA', '2B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20990674-0', 'PAMELA SOLEDAD', 'CALQUIN NUÑEZ', '3B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20509910-7', 'RAQUEL ANDREA', 'CANCINO FARIAS', '4B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20827695-6', 'JUAN ESTEBAN', 'CASTRO ESPINOZA', '5B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20692889-1', 'YASMIN ALEJANDRA', 'CIFUENTES JARAMILLO', '6B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20801567-2', 'BRAYAN ANTONIO', 'ESPINOZA MORALES', '7B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016117-1', 'ELIAS ANTONIO', 'FIGUEROA ALBURQUENQUE', '8B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802686-6', 'CATALINA ANTONIA', 'FLORES MURGA', '1B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21024793-9', 'ALINNE MICHELLE NADIESDA', 'FUENTES MANSILLA', '2B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016346-9', 'BARBARA NICOL', 'GONZALEZ ABACA', '3B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802215-6', 'CATHERINE NOELIA INES', 'GONZALEZ GONZALEZ', '4B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20564685-K', 'CRISCHNA CAMILA', 'GONZALEZ REBOLLEDO', '5B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('21016176-7', 'JENIFER KATALINA', 'GONZALEZ MEZA', '6B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20802619-4', 'FRANCISCA CAMILA', 'GONZALEZ RAMOS', '7B');
INSERT INTO student(rut, nombre, apellido, curso) VALUES('20904993-7', 'YICEL ANAIZ DEL PILAR', 'GONZALEZ BARRERA', '8B');